import { City } from './types';

// marketRent = loyer moyen marché €/m² (source : CLAMEUR / baromètre SeLoger 2024)
export const CITIES: City[] = [
  // ── Zone A bis ──────────────────────────────────────────────────────────────
  { name: 'Boulogne-Billancourt',     zone: 'A bis', marketRent: 26 },
  { name: 'Levallois-Perret',         zone: 'A bis', marketRent: 25 },
  { name: 'Neuilly-sur-Seine',        zone: 'A bis', marketRent: 28 },
  { name: 'Paris',                    zone: 'A bis', marketRent: 30 },

  // ── Zone A ──────────────────────────────────────────────────────────────────
  { name: 'Aix-en-Provence',          zone: 'A',     marketRent: 16 },
  { name: 'Ajaccio',                  zone: 'A',     marketRent: 15 },
  { name: 'Annecy',                   zone: 'A',     marketRent: 17 },
  { name: 'Annemasse',                zone: 'A',     marketRent: 16 },
  { name: 'Bayonne',                  zone: 'A',     marketRent: 14 },
  { name: 'Bordeaux',                 zone: 'A',     marketRent: 15 },
  { name: 'Chambéry',                 zone: 'A',     marketRent: 13 },
  { name: 'Cluses',                   zone: 'A',     marketRent: 11 },
  { name: 'Draguignan',               zone: 'A',     marketRent: 12 },
  { name: 'Fréjus',                   zone: 'A',     marketRent: 13 },
  { name: 'Grenoble',                 zone: 'A',     marketRent: 12 },
  { name: 'La Rochelle',              zone: 'A',     marketRent: 14 },
  { name: 'La Seyne-sur-Mer',         zone: 'A',     marketRent: 12 },
  { name: 'Le Havre',                 zone: 'A',     marketRent: 11 },
  { name: 'Libourne',                 zone: 'A',     marketRent: 12 },
  { name: 'Lyon',                     zone: 'A',     marketRent: 14 },
  { name: 'Mantes-la-Jolie',          zone: 'A',     marketRent: 16 },
  { name: 'Marseille',                zone: 'A',     marketRent: 13 },
  { name: 'Metz',                     zone: 'A',     marketRent: 10 },
  { name: 'Montpellier',              zone: 'A',     marketRent: 14 },
  { name: 'Nancy',                    zone: 'A',     marketRent: 11 },
  { name: 'Nantes',                   zone: 'A',     marketRent: 13 },
  { name: 'Nice',                     zone: 'A',     marketRent: 18 },
  { name: 'Nîmes',                    zone: 'A',     marketRent: 11 },
  { name: 'Rennes',                   zone: 'A',     marketRent: 13 },
  { name: 'Saint-Nazaire',            zone: 'A',     marketRent: 10 },
  { name: 'Strasbourg',               zone: 'A',     marketRent: 13 },
  { name: 'Thonon-les-Bains',         zone: 'A',     marketRent: 15 },
  { name: 'Toulon',                   zone: 'A',     marketRent: 13 },
  { name: 'Toulouse',                 zone: 'A',     marketRent: 13 },
  { name: 'Tours',                    zone: 'A',     marketRent: 11 },

  // ── Zone B1 ─────────────────────────────────────────────────────────────────
  { name: 'Amiens',                   zone: 'B1',    marketRent: 10 },
  { name: 'Angers',                   zone: 'B1',    marketRent: 11 },
  { name: 'Arles',                    zone: 'B1',    marketRent: 10 },
  { name: 'Avignon',                  zone: 'B1',    marketRent: 11 },
  { name: 'Besançon',                 zone: 'B1',    marketRent: 10 },
  { name: 'Brest',                    zone: 'B1',    marketRent: 10 },
  { name: 'Caen',                     zone: 'B1',    marketRent: 10 },
  { name: 'Chartres',                 zone: 'B1',    marketRent: 11 },
  { name: 'Cholet',                   zone: 'B1',    marketRent:  9 },
  { name: 'Clermont-Ferrand',         zone: 'B1',    marketRent: 10 },
  { name: 'Compiègne',                zone: 'B1',    marketRent: 11 },
  { name: 'Dijon',                    zone: 'B1',    marketRent: 11 },
  { name: 'Douai',                    zone: 'B1',    marketRent:  9 },
  { name: 'Dunkerque',                zone: 'B1',    marketRent:  9 },
  { name: 'La Roche-sur-Yon',         zone: 'B1',    marketRent: 10 },
  { name: 'Le Mans',                  zone: 'B1',    marketRent:  9 },
  { name: 'Lens',                     zone: 'B1',    marketRent:  8 },
  { name: 'Limoges',                  zone: 'B1',    marketRent:  8 },
  { name: 'Lorient',                  zone: 'B1',    marketRent: 10 },
  { name: 'Maubeuge',                 zone: 'B1',    marketRent:  8 },
  { name: 'Mulhouse',                 zone: 'B1',    marketRent:  8 },
  { name: 'Orléans',                  zone: 'B1',    marketRent: 11 },
  { name: 'Pau',                      zone: 'B1',    marketRent: 10 },
  { name: 'Perpignan',                zone: 'B1',    marketRent: 10 },
  { name: 'Poitiers',                 zone: 'B1',    marketRent: 10 },
  { name: 'Reims',                    zone: 'B1',    marketRent: 10 },
  { name: 'Rochefort',                zone: 'B1',    marketRent:  9 },
  { name: 'Rouen',                    zone: 'B1',    marketRent: 11 },
  { name: 'Saint-Étienne',            zone: 'B1',    marketRent:  8 },
  { name: 'Thionville',               zone: 'B1',    marketRent: 10 },
  { name: 'Valence',                  zone: 'B1',    marketRent: 10 },
  { name: 'Valenciennes',             zone: 'B1',    marketRent:  9 },

  // ── Zone B2 ─────────────────────────────────────────────────────────────────
  { name: 'Agen',                     zone: 'B2',    marketRent:  8 },
  { name: 'Albi',                     zone: 'B2',    marketRent:  8 },
  { name: 'Alençon',                  zone: 'B2',    marketRent:  8 },
  { name: 'Alès',                     zone: 'B2',    marketRent:  8 },
  { name: 'Angoulême',                zone: 'B2',    marketRent:  9 },
  { name: 'Arras',                    zone: 'B2',    marketRent:  9 },
  { name: 'Auch',                     zone: 'B2',    marketRent:  7 },
  { name: 'Aurillac',                 zone: 'B2',    marketRent:  7 },
  { name: 'Auxerre',                  zone: 'B2',    marketRent:  8 },
  { name: 'Bar-le-Duc',               zone: 'B2',    marketRent:  7 },
  { name: 'Bayeux',                   zone: 'B2',    marketRent:  9 },
  { name: 'Belfort',                  zone: 'B2',    marketRent:  8 },
  { name: 'Bergerac',                 zone: 'B2',    marketRent:  8 },
  { name: 'Béziers',                  zone: 'B2',    marketRent:  8 },
  { name: 'Blois',                    zone: 'B2',    marketRent:  9 },
  { name: 'Boulogne-sur-Mer',         zone: 'B2',    marketRent:  7 },
  { name: 'Bourges',                  zone: 'B2',    marketRent:  8 },
  { name: 'Brive-la-Gaillarde',       zone: 'B2',    marketRent:  8 },
  { name: 'Calais',                   zone: 'B2',    marketRent:  7 },
  { name: 'Carcassonne',              zone: 'B2',    marketRent:  8 },
  { name: 'Castres',                  zone: 'B2',    marketRent:  8 },
  { name: 'Châlons-en-Champagne',     zone: 'B2',    marketRent:  8 },
  { name: 'Charleville-Mézières',     zone: 'B2',    marketRent:  7 },
  { name: 'Châteauroux',              zone: 'B2',    marketRent:  7 },
  { name: 'Cherbourg-en-Cotentin',    zone: 'B2',    marketRent:  9 },
  { name: 'Colmar',                   zone: 'B2',    marketRent: 10 },
  { name: 'Dieppe',                   zone: 'B2',    marketRent:  8 },
  { name: 'Dreux',                    zone: 'B2',    marketRent:  9 },
  { name: 'Épinal',                   zone: 'B2',    marketRent:  7 },
  { name: 'Évreux',                   zone: 'B2',    marketRent:  9 },
  { name: 'Figeac',                   zone: 'B2',    marketRent:  8 },
  { name: 'Foix',                     zone: 'B2',    marketRent:  7 },
  { name: 'Fougères',                 zone: 'B2',    marketRent:  8 },
  { name: 'Gap',                      zone: 'B2',    marketRent:  9 },
  { name: 'Guéret',                   zone: 'B2',    marketRent:  6 },
  { name: 'Lannion',                  zone: 'B2',    marketRent:  9 },
  { name: 'Laon',                     zone: 'B2',    marketRent:  7 },
  { name: 'Laval',                    zone: 'B2',    marketRent:  8 },
  { name: 'Le Puy-en-Velay',          zone: 'B2',    marketRent:  7 },
  { name: 'Lisieux',                  zone: 'B2',    marketRent:  8 },
  { name: 'Lons-le-Saunier',          zone: 'B2',    marketRent:  8 },
  { name: 'Mâcon',                    zone: 'B2',    marketRent:  9 },
  { name: 'Mende',                    zone: 'B2',    marketRent:  7 },
  { name: 'Millau',                   zone: 'B2',    marketRent:  8 },
  { name: 'Montauban',                zone: 'B2',    marketRent:  9 },
  { name: 'Montélimar',               zone: 'B2',    marketRent:  9 },
  { name: 'Montluçon',                zone: 'B2',    marketRent:  7 },
  { name: 'Morlaix',                  zone: 'B2',    marketRent:  8 },
  { name: 'Moulins',                  zone: 'B2',    marketRent:  7 },
  { name: 'Narbonne',                 zone: 'B2',    marketRent:  9 },
  { name: 'Nevers',                   zone: 'B2',    marketRent:  7 },
  { name: 'Niort',                    zone: 'B2',    marketRent:  8 },
  { name: 'Périgueux',                zone: 'B2',    marketRent:  8 },
  { name: 'Péronne',                  zone: 'B2',    marketRent:  7 },
  { name: 'Privas',                   zone: 'B2',    marketRent:  7 },
  { name: 'Quimper',                  zone: 'B2',    marketRent:  9 },
  { name: 'Roanne',                   zone: 'B2',    marketRent:  8 },
  { name: 'Rodez',                    zone: 'B2',    marketRent:  8 },
  { name: 'Romans-sur-Isère',         zone: 'B2',    marketRent:  9 },
  { name: 'Saint-Brieuc',             zone: 'B2',    marketRent:  8 },
  { name: 'Saint-Dizier',             zone: 'B2',    marketRent:  7 },
  { name: 'Saint-Lô',                 zone: 'B2',    marketRent:  8 },
  { name: 'Saint-Malo',               zone: 'B2',    marketRent: 13 },
  { name: 'Saint-Omer',               zone: 'B2',    marketRent:  8 },
  { name: 'Saint-Quentin',            zone: 'B2',    marketRent:  7 },
  { name: 'Saintes',                  zone: 'B2',    marketRent:  8 },
  { name: 'Saumur',                   zone: 'B2',    marketRent:  9 },
  { name: 'Sedan',                    zone: 'B2',    marketRent:  6 },
  { name: 'Sens',                     zone: 'B2',    marketRent:  9 },
  { name: 'Soissons',                 zone: 'B2',    marketRent:  8 },
  { name: 'Tarbes',                   zone: 'B2',    marketRent:  8 },
  { name: 'Troyes',                   zone: 'B2',    marketRent:  9 },
  { name: 'Tulle',                    zone: 'B2',    marketRent:  7 },
  { name: 'Vannes',                   zone: 'B2',    marketRent: 12 },
  { name: 'Verdun',                   zone: 'B2',    marketRent:  7 },
  { name: 'Vesoul',                   zone: 'B2',    marketRent:  7 },
  { name: 'Vichy',                    zone: 'B2',    marketRent:  8 },
  { name: 'Vienne',                   zone: 'B2',    marketRent:  9 },
  { name: 'Villefranche-sur-Saône',   zone: 'B2',    marketRent:  9 },
];

export function searchCities(query: string): City[] {
  const normalized = query
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
  return CITIES.filter(city =>
    city.name
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .includes(normalized)
  ).slice(0, 10);
}
